<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="koala test 1"
           tests="4"
           failures="1"
           errors="0"
           skipped="1"
           time="0.001">
    <properties></properties>

            <testcase
                name="homePage"
                time="0.001"
                classname="com.techproed.tests.DependsOnMethods">

            <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
                org.testng.Assert.fail(Assert.java:97)org.testng.Assert.failNotEquals(Assert.java:969)org.testng.Assert.assertTrue(Assert.java:43)org.testng.Assert.assertTrue(Assert.java:53)com.techproed.tests.DependsOnMethods.homePage(DependsOnMethods.java:14)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:766)org.testng.TestRunner.run(TestRunner.java:587)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)org.testng.TestNG.runSuitesLocally(TestNG.java:1109)org.testng.TestNG.runSuites(TestNG.java:1039)org.testng.TestNG.run(TestNG.java:1007)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>

            <testcase
                name="searchTest"
                time="0.0"
                classname="com.techproed.tests.DependsOnMethods">
            </testcase>

            <testcase
                name="logIn"
                time="0.000"
                classname="com.techproed.tests.DependsOnMethods">
            </testcase>
            <testcase
                name="results"
                time="0.000"
                classname="com.techproed.tests.DependsOnMethods">
            </testcase>
</testsuite>
